# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reactnativetemplate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  # Pods for reactnativetemplate

  target 'reactnativetemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactnativetemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactnativetemplate-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactnativetemplate-tvOS

  target 'reactnativetemplate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
